name: Build Test

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set Git User
        run: |
          git config --global user.email "prince.francis@tociva.com"
          git config --global user.name "Tociva Technologies"

      - name: Increment version
        run: yarn version patch

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
