name: Build and Deploy to Development

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set Git User
        run: |
          git config --global user.email "prince.francis@tociva.com"
          git config --global user.name "Tociva Technologies"

      - name: Increment version
        run: yarn version patch

      - name: Get branch name
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          VERSION_FULL="v${VERSION}-${BRANCH_NAME}"
          echo "VERSION_FULL=$VERSION_FULL" >> $GITHUB_ENV

      - name: Update versions.md
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          {
            echo "# Version Details"
            echo "## Version: $VERSION"
            echo "## Date: $CURRENT_DATE"
            echo "BRANCH_NAME=$BRANCH_NAME"
            echo "BUILD_VERSION=$VERSION_FULL"
            echo ""
            cat versions.md
          } > versions.tmp && mv versions.tmp versions.md
      
      - name: Commit and Push Changes
        run: |
          git add package.json
          git add versions.md
          git commit -m "ci: bump version to $VERSION [skip ci]"
          git push origin HEAD:$BRANCH_NAME

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Angular App (production)
        run: yarn build --configuration production
            
      - name: Add deployment info to info.txt
        run: |
          mkdir -p dist/free-invoice-generator/browser
          
          # Write info.txt
          echo "branch : $BRANCH_NAME" > dist/free-invoice-generator/browser/info.txt
          echo "version : $VERSION" >> dist/free-invoice-generator/browser/info.txt
          echo "version_full : $VERSION_FULL" >> dist/free-invoice-generator/browser/info.txt
          echo "time : $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> dist/free-invoice-generator/browser/info.txt

      - name: Deploy to Cloudflare Pages with Wrangler
        run: |
          yarn dlx wrangler pages deploy dist/free-invoice-generator/browser \
            --project-name ${{ secrets.CF_PROJECT_NAME }} \
            --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID:        ${{ secrets.CF_ACCOUNT_ID }}

      - name: Create and Push Tag
        run: |
          TAG_NAME="${{ env.VERSION_FULL }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME


