name: Build and Deploy to Development

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Angular App (production)
        run: yarn build --configuration production

      - name: Increment version and push to master
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Increment version
          yarn version --patch --no-git-tag-version

          # Get version from package.json and export to workflow env
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          git add package.json
          git commit -m "ci: bump version to $VERSION before deployment [skip ci]"
          git push origin HEAD:master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add deployment info to info.txt
        run: |
          mkdir -p dist/free-invoice-generator/browser
          
          # Extract and export branch name
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          # Write info.txt
          echo "branch : $BRANCH_NAME" > dist/free-invoice-generator/browser/info.txt
          echo "version : $VERSION" >> dist/free-invoice-generator/browser/info.txt
          echo "time : $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> dist/free-invoice-generator/browser/info.txt

      - name: Deploy to Cloudflare Pages with Wrangler
        run: |
          yarn dlx wrangler pages deploy dist/free-invoice-generator/browser \
            --project-name ${{ secrets.CF_PROJECT_NAME }} \
            --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID:        ${{ secrets.CF_ACCOUNT_ID }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
            
      - name: Get User, Release Date and Time
        run: |
          echo "RELEASE_DATETIME=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
          echo "RELEASE_USER=${{ github.actor }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '${BRANCH_NAME}-${VERSION}'
          name: 'Development Release ${BRANCH_NAME}-${VERSION}'
          body: |
            ## Release Details
            - **Title:** `Development Release ${BRANCH_NAME}-${VERSION}`
            - **Environment:** `Development`
            - **Branch:** `${BRANCH_NAME}`
            - **Version:** `${VERSION}`
            - **Version Full Name:** `${BRANCH_NAME}-${VERSION}`
            - **Release Date:** `${{ env.RELEASE_DATETIME }}`
            - **Released By:** `${{ env.RELEASE_USER }}`
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


