name: Build and Deploy to Development

on:
  pull_request:
    branches: [main]
    types: [closed]  # Only run when PR is closed

  workflow_dispatch:  # Allow manual runs

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true  # ✅ Only continue if PR was merged
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Angular (development config)
        run: npm run build --configuration development

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          wrangler pages deploy dist/<your-angular-project-name> \
            --project-name ${{ secrets.CF_PROJECT_NAME }} \
            --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID:        ${{ secrets.CF_ACCOUNT_ID }}
